# Stage 1: Build Angular SSR
FROM node:22-alpine AS build
WORKDIR /app

COPY shared ./shared

COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# Stage 2: Runtime Node SSR
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/dist/frontend /app/dist/frontend
COPY frontend/package*.json ./
RUN npm ci

EXPOSE 4000
CMD ["npm", "run", "serve:ssr:frontend"]