export type GameStatus = 'WAITING_FOR_PLAYERS' | 'PLAYING' | 'GAME_ENDED';

export const GameStatus = {
  WAITING_FOR_PLAYERS: 'WAITING_FOR_PLAYERS',
  PLAYING: 'PLAYING',
  GAME_ENDED: 'GAME_ENDED',
};
